export enum Role {
    ROLE_ADMIN = "ROLE_ADMIN",
    ROLE_AUTHORIZED = "ROLE_AUTHORIZED",
    ROLE_STUDENT = "ROLE_STUDENT",
    ROLE_TEACHER = "ROLE_TEACHER",
    ROLE_PARENT = "ROLE_PARENT",
    ROLE_GUEST = "ROLE_GUEST",
}